env:
  global:
    - CC_TEST_REPORTER_ID=2e401bc26dc9709d31542e7431103d702a3901566f5a3226460cb3acdc8dffce
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)

language: node_js
node_js:
  - stable

script:
  - make lint
  - make test

addons:
  code_climate:
    repo_token: 2e401bc26dc9709d31542e7431103d702a3901566f5a3226460cb3acdc8dffce
